const mongoose = require('mongoose');
const { Schema } = mongoose;

const printDiputadosD1Schema = new Schema({
    
    municipio: {type: String, required: true},
    centro: {type: String, required: true},
    colegio: {type: String, required: true},
    votosValidos: {type: Number, required: true},
    votosEmitidos: {type: Number, required: true},
    votosNulos: {type: Number, required: true},
    boletasObservadas: {type: Number, required: true},
    // diputadosArray: {type: Array, required: true},
    pld1: {type: Number, required: true},
    pld2: {type: Number, required: true},
    pld3: {type: Number, required: true},
    pld4: {type: Number, required: true},
    pld5: {type: Number, required: true},
    prm1: {type: Number, required: true},
    prm2: {type: Number, required: true},
    prm3: {type: Number, required: true},
    prm4: {type: Number, required: true},
    prm5: {type: Number, required: true},
    prsc1: {type: Number, required: true},
    prsc2: {type: Number, required: true},
    prsc3: {type: Number, required: true},
    prsc4: {type: Number, required: true},
    prsc5: {type: Number, required: true},
    prd1: {type: Number, required: true},
    prd2: {type: Number, required: true},
    prd3: {type: Number, required: true},
    prd4: {type: Number, required: true},
    prd5: {type: Number, required: true},
    moda1: {type: Number, required: true},
    moda2: {type: Number, required: true},
    moda3: {type: Number, required: true},
    moda4: {type: Number, required: true},
    moda5: {type: Number, required: true},
    famplio1: {type: Number, required: true},
    famplio2: {type: Number, required: true},
    famplio3: {type: Number, required: true},
    famplio4: {type: Number, required: true},
    famplio5: {type: Number, required: true},
    alpais1: {type: Number, required: true},
    alpais2: {type: Number, required: true},
    alpais3: {type: Number, required: true},
    alpais4: {type: Number, required: true},
    alpais5: {type: Number, required: true},
    plr1: {type: Number, required: true},
    plr2: {type: Number, required: true},
    plr3: {type: Number, required: true},
    plr4: {type: Number, required: true},
    plr5: {type: Number, required: true},
    pal1: {type: Number, required: true},
    pal2: {type: Number, required: true},
    pal3: {type: Number, required: true},
    pal4: {type: Number, required: true},
    pal5: {type: Number, required: true},
    pnvc1: {type: Number, required: true},
    pnvc2: {type: Number, required: true},
    pnvc3: {type: Number, required: true},
    pnvc4: {type: Number, required: true},
    pnvc5: {type: Number, required: true},
    pp1: {type: Number, required: true},
    pp2: {type: Number, required: true},
    pp3: {type: Number, required: true},
    pp4: {type: Number, required: true},
    pp5: {type: Number, required: true},
    
});

module.exports = mongoose.model('PrintDiputadosD1', printDiputadosD1Schema);

